[package]
name = "tokio-async-crawler"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.38.0", features = ["full"] }
reqwest = { version = "0.12", features = ["json"] }
json = "0.12.4"
openssl = { version = "0.10", features = ["vendored"] }