[package]
name = "async-await"
version = "0.1.0"
edition = "2024"

# 提供无锁队列
[dependencies.crossbeam-queue]
version = "0.2.1"
default-features = false
features = ["alloc"]

# 提供无锁、线程安全的 OnceCell
[dependencies.conquer-once]
version = "0.2.0"
default-features = false